apiVersion: v2
name: "magda-local-auth-test-deployment"
description: ""
version: "2.1.1"
kubeVersion: ">= 1.14.0-0"
dependencies:
  - name: magda-core
    version: 2.1.1
    repository: "file://../magda-core"
