apiVersion: v2
name: "magda-local-auth-test-deployment"
description: ""
version: "3.0.2"
kubeVersion: ">= 1.14.0-0"
dependencies:
  - name: magda-core
    version: 3.0.2
    repository: "file://../magda-core"
