apiVersion: v2
name: "magda-local-auth-test-deployment"
description: ""
version: "6.0.0-alpha.9"
kubeVersion: ">= 1.14.0-0"
dependencies:
  - name: magda-core
    version: 6.0.0-alpha.9
    repository: "file://../magda-core"
