apiVersion: v2
name: "magda-local-auth-test-deployment"
description: ""
version: "4.2.5"
kubeVersion: ">= 1.14.0-0"
dependencies:
  - name: magda-core
    version: 4.2.5
    repository: "file://../magda-core"
