apiVersion: v2
name: "magda-local-auth-test-deployment"
description: ""
version: "1.0.0-alpha.2"
kubeVersion: ">= 1.14.0-0"
dependencies:
  - name: magda-core
    version: 1.0.0-alpha.2
    repository: "file://../magda-core"
