apiVersion: v2
name: my-magda-app
description: A Helm chart for Kubernetes
version: "2.0.0-alpha.4"
kubeVersion: ">= 1.16.0-0"
dependencies:
  - name: magda
    version: 2.0.0-alpha.4
    repository: https://charts.magda.io

  - name: magda-auth-internal
    version: 1.2.3
    repository: https://charts.magda.io
    tags:
      - all
      - magda-auth-internal

  - name: magda-auth-google
    version: 1.2.3
    repository: https://charts.magda.io
    tags:
      - all
      - magda-auth-google

  - name: magda-ckan-connector
    version: 1.3.0
    alias: connector-dga
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-dga
