build:authorization-api:
  stage: build
  image: data61/magda-builder-nodejs:0.0.38-0
  dependencies: 
  - prebuild:typescript-common
  script:
    - lerna bootstrap --scope=@magda/authorization-api 
    - lerna run build --scope=@magda/authorization-api 
  artifacts:
    paths:
    - "node_modules"
    - "*/dist"
    - "*/node_modules"
    expire_in: 30 minutes

# test:authorization-api:
#   stage: test
#   image: data61/magda-builder-nodejs:0.0.38-0
#   dependencies: 
#   - build:authorization-api
#   cache:
#     paths: []
#   script:
#     - lerna bootstrap --scope=@magda/authorization-api 
#     - lerna run test --scope=@magda/authorization-api
