apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: {{- if .Values.useStaging }} "https://acme-staging-v02.api.letsencrypt.org/directory" {{- else }} https://acme-v02.api.letsencrypt.org/directory {{- end }}
    email: {{ .Values.acmeEmail }}

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt

    solvers:
    # ACME DNS-01 provider configurations
    - selector:
        dnsZones:
          - "environment.magda.io"
      dns01:
        route53:
          region: ap-southeast-2
          hostedZoneID: {{ .Values.hostedZoneID }}
          accessKeyID: {{ .Values.accessKeyID }}
          secretAccessKeySecretRef:
            name: {{ .Values.secretAccessKeySecretRef.name }}
            key: {{ .Values.secretAccessKeySecretRef.key }}