apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  template:
    metadata:
      labels:
        service: gateway
    spec:
      containers:
      - name: gateway
        image: {{ template "dockerimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
        command: [
            "node",
            "/usr/src/app/component/dist/index.js",
            "--listenPort", "80",
            "--externalUrl", {{ .Values.global.externalUrl | quote }},
            {{- if .Values.ckanRedirectionDomain }}
            "--ckanRedirectionDomain", {{ .Values.ckanRedirectionDomain | quote }},
            {{- end }}
            {{- if .Values.ckanRedirectionPath }}
            "--ckanRedirectionPath", {{ .Values.ckanRedirectionPath | quote }},
            {{- end }}
            "--dbHost", "session-db",
            "--dbPort", "5432",
{{- if .Values.auth.facebookClientId }}
            "--facebookClientId", {{ .Values.auth.facebookClientId | quote }},
{{- end }}
{{- if .Values.auth.googleClientId }}
            "--googleClientId", {{ .Values.auth.googleClientId | quote }},
{{- end }}
{{- if .Values.enableAuthEndpoint }}
            "--enableAuthEndpoint", {{ .Values.enableAuthEndpoint | quote }},
{{- end }}
{{- if .Values.enableWebAccessControl }}
            "--enableWebAccessControl", {{ .Values.enableWebAccessControl | quote }},
{{- end }}
            "--proxyRoutesJson", "/etc/config/routes.json",
            "--helmetJson", "/etc/config/helmet.json",
            "--cspJson", "/etc/config/csp.json",
            "--corsJson", "/etc/config/cors.json",
            "--web", "http://web",
            "--authorizationApi", "http://authorization-api/v0",
            "--previewMap", "http://preview-map:6110",
            "--ckanUrl", "https://data.gov.au"
        ]
        volumeMounts:
          - name: config
            mountPath: /etc/config
        readinessProbe:
          httpGet:
            path: /v0/healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
{{- if .Values.global.enableLivenessProbes }}
        livenessProbe:
          httpGet:
            path: /v0/healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: NODE_ENV
          value: production
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
{{- if .Values.enableWebAccessControl }}
        - name: WEB_ACCESS_USERNAME
          valueFrom:
            secretKeyRef:
              name: web-access-secret
              key: username
        - name: WEB_ACCESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: web-access-secret
              key: password
{{- end }}
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: session-secret
        - name: USER_ID
          value: {{ .Values.global.defaultAdminUserId }}
{{- if .Values.auth.facebookClientId }}
        - name: FACEBOOK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: facebook-client-secret
              optional: true
{{- end }}
{{- if .Values.auth.googleClientId }}
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: google-client-secret
              optional: true
{{- end }}
{{- if .Values.global.noDbAuth }}
        - name: PGUSER
          value: client
{{- else }}
        - name: PGUSER
          value: client
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-passwords
              key: session-db-client
{{- end }}
      volumes:
        - name: config
          configMap:
            name: gateway-config
