dist: trusty
sudo: false
matrix:
  include:
    - language: scala
      scala: 2.11.8
      jdk: oraclejdk8
      services:
        - postgresql
        - docker
      cache:
        directories:
          - $HOME/.ivy2/cache
          - $HOME/.sbt
          - target
      before_cache:
        # Cleanup the cached directories to avoid unnecessary cache updates
        - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
        - find $HOME/.sbt        -name "*.lock"               -print -delete
      env:
        global:
          # 3gb heap, unload classes we don't need, aim for < 50ms gc pauses (largely ignored), use the next-gen collector, try to free 5% of heap every gc, use < 25% of time for GC
          - SBT_OPTS="-Xms3000M -Xmx3000M -XX:+CMSClassUnloadingEnabled -XX:MaxGCPauseMillis=1000 -XX:+UseG1GC -XX:GCTimeRatio=3"
          - CI=true
          - REACT_APP_SHA1=$TRAVIS_COMMIT
      addons:
        postgresql: "9.6"
      before_install:
        - docker info
        - docker-compose --version
      script: 
        - cd magda-elastic-search
        - docker-compose up -d
        - cd ..
        - travis_retry sbt test
        - cd magda-elastic-search
        - docker-compose down
    - language: node_js
      node_js: "8"
      cache:
        directories:
          - $HOME/.ivy2/cache
          - $HOME/.sbt
          - .yarn
      before_install:
        - yarn config set cache-folder .yarn
      before_cache:
        # Cleanup the cached directories to avoid unnecessary cache updates
        - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
        - find $HOME/.sbt        -name "*.lock"               -print -delete
      script:
        - yarn run in-submodules -- -f categories.api=true -f language=typescript -- run build --include-filtered-dependencies
        - yarn run in-submodules -- -f categories.api=true -f language=typescript -- run test
        - yarn run in-submodules -- -f categories.connector=true -- run build --include-filtered-dependencies
        - yarn run in-submodules -- -f categories.connector=true -- run test
        - yarn run in-submodules -- -f categories.minion=true -- run build --include-filtered-dependencies
        - yarn run in-submodules -- -f categories.minion=true -- run test
      env:
        global:
          - CI=true
    - language: node_js
      node_js: "8"
      cache:
        directories:
          - .yarn
      before_install:
        - yarn config set cache-folder .yarn
      script:
        - yarn global add lerna
        - yarn run eslint
        - cd magda-preview-map && npm rebuild node-sass && cd ..
        - lerna run build --scope @magda/web-client --scope @magda/preview-map --include-filtered-dependencies
        - lerna run test --scope @magda/preview-map --scope @magda/web-client
      env:
        global:
          - CI=true
