{{- if and (not .Values.global.useCombinedDb) (not .Values.global.useCloudSql) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tenant-db
spec:
  serviceName: tenant-db
  replicas: 1
  selector:
    matchLabels:
      service: tenant-db
  template:
    metadata:
      labels:
        service: tenant-db
    spec:
{{- if and (.Capabilities.APIVersions.Has "scheduling.k8s.io/v1beta1") .Values.global.enablePriorityClass }}
      priorityClassName: magda-9
{{- end }}
      terminationGracePeriodSeconds: 60
      affinity:
{{- if .Values.affinity }}
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
      containers:
      - name: tenant-db
        resources:
{{ toYaml .Values.resources | indent 10 }}
        image: {{ template "postgres" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
        ports:
        - containerPort: 5432
        {{- template "magda.postgresLivenessProbe" . }}
        env:
        - name: PGDATA
          value: /var/pv/data
        {{- template "magda.postgres-env" . }}
        volumeMounts:
        - mountPath: /var/pv
          name: tenant-data
        {{- template "magda.waleVolumes.volumeMount" . }}
      volumes:
      {{- template "magda.waleVolumes.volume" . }}
  volumeClaimTemplates:
  - metadata:
      name: tenant-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
    {{- if .Values.data.storageClass }}
      storageClassName: "{{ .Values.data.storageClass }}"
    {{- end }}
      resources:
        requests:
          storage: "{{ .Values.data.storage }}"
{{- end }}
