apiVersion: v1
kind: Service
metadata:
  name: semantic-search-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.semanticSearchConfig.listenPort }}
  selector:
    service: semantic-search-api
