apiVersion: v2
name: magda-postgres
description: "A helm wrapper chart that provides in-kubernetes postgreSQL for Magda."
type: application
kubeVersion: ">= 1.21.0"
version: "2.2.4-alpha.0"
annotations:
  magdaModuleType: "core"
dependencies:
  - name: postgresql
    version: "10.9.1"
    repository: "https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami"
