apiVersion: v2
name: "magda-local-deployment"
description: ""
version: "3.0.1-alpha.0"
kubeVersion: ">= 1.14.0-0"
dependencies:
  - name: magda
    version: 3.0.1-alpha.0
    repository: "file://../magda"

  - name: magda-auth-google
    version: "2.0.1"
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - all
      - magda-auth-google

  - name: magda-auth-internal
    version: "2.0.0"
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - all
      - magda-auth-internal

  - name: magda-auth-arcgis
    version: "2.0.1"
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - all
      - magda-auth-arcgis

  - name: magda-auth-facebook
    version: "2.0.0"
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - all
      - magda-auth-facebook

  ## Data.gov.au connector to provide some initial data. Remove this if you
  ## don't want any data.gov.au connector
  - name: magda-ckan-connector
    version: "2.1.0"
    alias: connector-dga
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-dga

  - name: magda-project-open-data-connector
    version: "2.0.0"
    alias: connector-act
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-act

  - name: magda-project-open-data-connector
    version: "2.0.0"
    alias: connector-actmapi
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-actmapi
  # aodn already includes most datasets from aims
  # - name: magda-csw-connector
  #   version: "2.0.2"
  #   alias: connector-aims
  #   repository: "oci://ghcr.io/magda-io/charts"
  #   tags:
  #     - connectors
  #     - connector-aims
  - name: magda-csw-connector
    version: "2.0.2"
    alias: connector-aodn
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-aodn
  - name: magda-csw-connector
    version: "2.0.2"
    alias: connector-bom
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-bom
  - name: magda-ckan-connector
    version: "2.1.0"
    alias: connector-aurin
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-aurin
  - name: magda-ckan-connector
    version: "2.1.0"
    alias: connector-brisbane
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-brisbane
  - name: magda-project-open-data-connector
    version: "2.0.0"
    alias: connector-hobart
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-hobart
  - name: magda-project-open-data-connector
    version: "2.0.0"
    alias: connector-launceston
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-launceston
  - name: magda-csw-connector
    version: "2.0.2"
    alias: connector-marlin
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-marlin
  - name: magda-csw-connector
    version: "2.0.2"
    alias: connector-environment
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-environment
  - name: magda-csw-connector
    version: "2.0.2"
    alias: connector-ga
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-ga
  - name: magda-project-open-data-connector
    version: "2.0.0"
    alias: connector-logan
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-logan
  - name: magda-project-open-data-connector
    version: "2.0.0"
    alias: connector-melbournewater
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-melbournewater
  - name: magda-project-open-data-connector
    version: "2.0.0"
    alias: connector-melbourne
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-melbourne
  - name: magda-csw-connector
    version: "2.0.2"
    alias: connector-mrt
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-mrt
  - name: magda-project-open-data-connector
    version: "2.0.0"
    alias: connector-moretonbay
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-moretonbay
  - name: magda-csw-connector
    version: "2.0.2"
    alias: connector-neii
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-neii
  - name: magda-ckan-connector
    version: "2.1.0"
    alias: connector-nsw
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-nsw
  - name: magda-csw-connector
    version: "2.0.2"
    alias: connector-sdinsw
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-sdinsw
  - name: magda-ckan-connector
    version: "2.1.0"
    alias: connector-qld
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-qld
  - name: magda-ckan-connector
    version: "2.1.0"
    alias: connector-sa
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-sa
  - name: magda-project-open-data-connector
    version: "2.0.0"
    alias: connector-southerngrampians
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-southerngrampians
  - name: magda-csw-connector
    version: "2.0.2"
    alias: connector-listtas
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-listtas
  - name: magda-csw-connector
    version: "2.0.2"
    alias: connector-tern
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-tern
  - name: magda-ckan-connector
    version: "2.1.0"
    alias: connector-vic
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-vic
  - name: magda-ckan-connector
    version: "2.1.0"
    alias: connector-wa
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-wa
  - name: magda-dap-connector
    version: "2.0.0"
    alias: connector-dap
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-dap
  - name: magda-project-open-data-connector
    version: "2.0.0"
    alias: connector-vic-cardinia
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-vic-cardinia
  - name: magda-project-open-data-connector
    version: "2.0.0"
    alias: connector-nt-darwin
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-nt-darwin
  - name: magda-project-open-data-connector
    version: "2.0.0"
    alias: connector-southern-grampians
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-southern-grampians
