apiVersion: v1
kind: ConfigMap
metadata:
  name: "config"
data:
  # When the config map is mounted as a volume, these will be created as files.
  web.json: '{
    "disableAuthenticationFeatures": false,
    "baseUrl": "/"
  }'