global:
    useCombinedDb: false
    useCloudSql: true
    externalUrl: https://search.data.gov.au
    image:
        pullPolicy: IfNotPresent
        tag: "0.0.38-RC2"
tags:
    all: false

    authorization-api: true
    authorization-db: true
    elasticsearch: true
    gateway: true
    indexer: true
    preview-map: true
    registry-api: true
    registry-db: true
    search-api: true
    session-db: true
    sleuther-broken-link: true
    sleuther-linked-data-rating: true
    sleuther-visualization: true
    sleuther-format: true
    web-server: true
    feedback-api: true

elasticsearch:
    production: true
    client:
        replicas: 2
        heapSize: 900m
        pluginsInstall: "repository-gcs"
        resources:
            requests:
                cpu: 200m
                memory: 1500Mi
    data:
        heapSize: 3000m
        pluginsInstall: "repository-gcs"
        storageClass: "fast-ssd"
        resources:
            requests:
                cpu: 800m
                memory: 5000Mi
gateway:
    loadBalancerIP: "35.189.8.102"
    autoscaler:
        minReplicas: 2
        maxReplicas: 4
    auth:
        facebookClientId: "173073926555600"
        googleClientId: "275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com"
    resources:
        requests:
            cpu: 200m
            memory: 200Mi
preview-map:
    replicas: 2
    resources:
        requests:
            cpu: 250m
            memory: 200Mi
registry-api:
    logLevel: INFO
    requests:
        cpu: 500m
        memory: 1000Mi
registry-db:
    resources:
        requests:
            cpu: 900m
            memory: 2000Mi
    data:
        storageClass: "fast-ssd"
    waleBackup:
        method: WAL
        gsPrefix: "gs://magda-postgres-backups/prod/registry"
        executionTime: 03:00
        googleApplicationCreds:
            secretName: storage-account-credentials
            fileName: TerriaJS-5e042b649f8a.json
authorization-db:
    resources:
        requests:
            cpu: 250m
            memory: 500Mi
    data:
        storageClass: "fast-ssd"
    waleBackup:
        method: WAL
        gsPrefix: "gs://magda-postgres-backups/prod/authorization"
        executionTime: 03:00
        googleApplicationCreds:
            secretName: storage-account-credentials
            fileName: TerriaJS-5e042b649f8a.json
session-db:
    data:
        storageClass: "fast-ssd"
    resources:
        requests:
            cpu: 250m
            memory: 500Mi
authorization-api:
    replicas: 2
    requests:
        cpu: 100m
        memory: 200Mi
search-api:
    replicas: 2
    requests:
        cpu: 250m
        memory: 200Mi
    limits:
        cpu: 1000m
        memory: 1000m
web-server:
    autoscaler:
        minReplicas: 2
        maxReplicas: 4
    resources:
        requests:
            cpu: 250m
            memory: 200Mi
    disableAuthenticationFeatures: true
sleuther-broken-link:
    resources:
        requests:
            cpu: 100m
            memory: 200Mi
        limits:
            cpu: 500m
            memory: 500Mi
sleuther-linked-data-rating:
    resources:
        requests:
            cpu: 100m
            memory: 200Mi
        limits:
            cpu: 500m
            memory: 500Mi
sleuther-visualization:
    resources:
        requests:
            cpu: 100m
            memory: 200Mi
        limits:
            cpu: 500m
            memory: 500Mi
sleuther-format:
    resources:
        requests:
            cpu: 100m
            memory: 200Mi
        limits:
            cpu: 500m
            memory: 500Mi
indexer:
  elasticsearch:
    shards: 2
    replicas: 4
#    useGcsSnapshots: true
#    gcsSnapshotBucket: "magda-es-snapshots"
#    gcsSnapshotServiceAccount: "_default"
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
feedback-api:
    gitHubIssuesUrl: "https://api.github.com/repos/TerriaJS/Magda-Feedback/issues"
    replicas: 2
cloud-sql-proxy:
    replicas: 2
    instanceConnectionName: terriajs:australia-southeast1:magda-prod
