apiVersion: apps/v1
kind: Deployment
metadata:
  name: preview-map
spec:
  replicas: {{ .Values.replicas | default 1 }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  selector:
    matchLabels:
      service: preview-map
  template:
    metadata:
      labels:
        service: preview-map
    spec:
{{- $imagePullSecret := (ne (.Values.image.imagePullSecret | typeOf) "<nil>") | ternary .Values.image.imagePullSecret ( (ne (.Values.global.image.imagePullSecret | typeOf) "<nil>") | ternary .Values.global.image.imagePullSecret .Values.defaultImage.imagePullSecret ) -}}
      {{- if ne ($imagePullSecret | toString) "false" }}
      imagePullSecrets:
        - name: {{ $imagePullSecret }}
      {{- end }}
      containers:
      - name: preview-map
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- if .Values.global.enableLivenessProbes }}
        livenessProbe:
          httpGet:
            path: ""
            port: 6110
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
{{- end }}
        env:
        - name: NODE_ENV
          value: production
        image: "{{ .Values.image.repository | default .Values.global.image.repository | default .Values.defaultImage.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Values.global.image.tag | default .Values.defaultImage.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
