{{- if and (.Capabilities.APIVersions.Has "scheduling.k8s.io/v1beta1") .Values.global.enablePriorityClass }}
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: magda-1
value: 10000000
globalDefault: false
description: "Ordered importance class 1-10"
{{- end }}