{{- if .Capabilities.APIVersions.Has "scheduling.k8s.io/v1beta1" }}
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: magda-0
value: 0
globalDefault: true
description: "Ordered importance class 1-10"
{{- end }}