
apiVersion: v1
kind: ConfigMap
metadata:
  name: "connector-config"
data:
  # When the config map is mounted as a volume, these will be created as files.
{{- range .Values.config }}
  {{ .id }}.json: '{{ toJson . }}'
{{- end }}