# Postgres for Auth
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: combined-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: combined-db
    spec:
      containers:
      - name: combined-db
        image: localhost:5000/data61/magda-combined-db:latest
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
      volumes:
      - name: data
        hostPath:
          path: /tmp/combinedDbData
---
apiVersion: v1
kind: Service
metadata:
  name: combined-db
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    nodePort: 30545
  selector:
    service: combined-db
  type: "NodePort"
