apiVersion: v2
description: A Helm chart for Kubernetes
name: storage-api
version: 0.0.60-alpha.0
kubeVersion: ">= 1.14.0-0"
dependencies:
  - name: minio
    version: 7.1.2
    repository: https://helm.min.io
