apiVersion: v2
description: A Helm chart for Kubernetes
name: storage-api
version: 2.0.0-alpha.3
kubeVersion: ">= 1.14.0-0"
annotations:
  magdaModuleType: "core"
dependencies:
  - name: minio
    version: 7.1.2
    repository: https://helm.min.io
