{{- if and (.Capabilities.APIVersions.Has "scheduling.k8s.io/v1beta1") .Values.global.enablePriorityClass }}
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: magda-0
value: 0
description: "Ordered importance class 1-10"
{{- end }}