apiVersion: v1
kind: Service
metadata:
  name: registry-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
{{- if .Values.global.exposeNodePorts }}
    nodePort: 30101
  type: NodePort
{{- end }}
  selector:
    service: registry-api-full
