{{- if and .Values.global.exposeNodePorts .Values.global.useCombinedDb }}
apiVersion: v1
kind: Service
metadata:
  name: combined-db
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    nodePort: 30432
  type: NodePort
  selector:
    service: combined-db
{{- end }}
