apiVersion: v2
description: The Gateway Component of Magda that routes incoming requets to
  other magda components.
name: gateway
version: 1.1.0-alpha.0
kubeVersion: ">= 1.14.0-0"
annotations:
  magdaModuleType: "core"
