{{ if .Values.autoscaler.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: content-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: content-api
  minReplicas: {{ .Values.autoscaler.minReplicas }}
  maxReplicas: {{ .Values.autoscaler.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.autoscaler.targetCPUUtilizationPercentage }}
{{ end }}
