dependencies:
  - name: admin-api
    version: 0.1.0
    tags:
      - all
      - admin-api
  - name: authorization-api
    version: 0.1.0
    tags:
      - all
      - authorization-api
  - name: authorization-db
    version: 0.1.0
    tags:
      - all
      - authorization-db
  - name: combined-db
    version: 0.1.0
    tags:
      - all
      - combined-db
  - name: discussions-api
    version: 0.1.0
    tags:
      - all
      - discussions-api
  - name: discussions-db
    version: 0.1.0
    tags:
      - all
      - discussions-db
  - name: elasticsearch
    version: 0.1.0
    tags:
      - all
      - elasticsearch
  - name: feedback-api
    version: 0.1.0
    tags:
      - all
      - feedback-api
  - name: gateway
    version: 0.1.0
    tags:
      - all
      - gateway
  - name: indexer
    version: 0.1.0
    tags:
      - all
      - indexer
  - name: preview-map
    version: 0.1.0
    tags:
      - all
      - preview-map
  - name: registry-api
    version: 0.1.0
    tags:
      - all
      - registry-api
  - name: registry-db
    version: 0.1.0
    tags:
      - all
      - registry-db
  - name: search-api
    version: 0.1.0
    tags:
      - all
      - search-api
  - name: session-db
    version: 0.1.0
    tags:
      - all
      - session-db
  - name: sleuther-format
    version: 0.1.0
    tags:
      - all
      - sleuther-format
  - name: sleuther-broken-link
    version: 0.1.0
    tags:
      - all
      - sleuther-broken-link
  - name: sleuther-visualization
    version: 0.1.0
    tags:
      - all
      - sleuther-visualization
  - name: sleuther-linked-data-rating
    version: 0.1.0
    tags:
      - all
      - sleuther-linked-data-rating
  - name: web-server
    version: 0.1.0
    tags:
      - all
      - web-server
