dependencies:
  - name: magda-core
    version: 0.0.57-0
    repository: file://../magda-core
  # magda-core chart is always enabled.
  # Thus, no tags or condition are required.
  # You should set its sub-chart to enabled or not.

  - name: magda-minion-broken-link
    alias: minion-broken-link
    version: 0.0.57-0
    repository: https://charts.magda.io
    tags:
      - minions
      - minion-broken-link

  - name: magda-minion-format
    alias: minion-format
    version: 0.0.57-0
    repository: https://charts.magda.io
    tags:
      - minions
      - minion-format

  - name: magda-minion-linked-data-rating
    alias: minion-linked-data-rating
    version: 0.0.57-0
    repository: https://charts.magda.io
    tags:
      - minions
      - minion-linked-data-rating

  - name: magda-minion-visualization
    alias: minion-visualization
    version: 0.0.57-0
    repository: https://charts.magda.io
    tags:
      - minions
      - minion-visualization

  - name: magda-minion-ckan-publisher
    version: 0.0.57-0
    alias: minion-ckan-publisher
    repository: https://charts.magda.io
    tags:
      - minions
      - minion-ckan-publisher

  - name: magda-ckan-connector
    version: 0.0.57-0
    alias: ckan-connector-functions
    repository: https://charts.magda.io
    tags:
      - all
      - url-processors
      - ckan-connector-functions

  - name: magda-ckan-connector
    version: 0.0.57-0
    alias: connector-dga
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-dga

  - name: magda-project-open-data-connector
    version: 0.0.57-0
    alias: connector-act
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-act

  - name: magda-project-open-data-connector
    version: 0.0.57-0
    alias: connector-actmapi
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-actmapi

  - name: magda-csw-connector
    version: 0.0.57-0
    alias: connector-aims
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-aims

  - name: magda-csw-connector
    version: 0.0.57-0
    alias: connector-aodn
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-aodn

  - name: magda-csw-connector
    version: 0.0.57-0
    alias: connector-bom
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-bom

  - name: magda-csw-connector
    version: 0.0.57-0
    alias: connector-aurin
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-aurin

  - name: magda-ckan-connector
    version: 0.0.57-0
    alias: connector-brisbane
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-brisbane

  - name: magda-project-open-data-connector
    version: 0.0.57-0
    alias: connector-hobart
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-hobart

  - name: magda-project-open-data-connector
    version: 0.0.57-0
    alias: connector-launceston
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-launceston

  - name: magda-csw-connector
    version: 0.0.57-0
    alias: connector-marlin
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-marlin

  - name: magda-csw-connector
    version: 0.0.57-0
    alias: connector-environment
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-environment

  - name: magda-project-open-data-connector
    version: 0.0.57-0
    alias: connector-esta
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-esta

  - name: magda-csw-connector
    version: 0.0.57-0
    alias: connector-ga
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-ga

  - name: magda-project-open-data-connector
    version: 0.0.57-0
    alias: connector-logan
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-logan

  - name: magda-project-open-data-connector
    version: 0.0.57-0
    alias: connector-melbournewater
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-melbournewater

  - name: magda-project-open-data-connector
    version: 0.0.57-0
    alias: connector-melbourne
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-melbourne

  - name: magda-csw-connector
    version: 0.0.57-0
    alias: connector-mrt
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-mrt

  - name: magda-project-open-data-connector
    version: 0.0.57-0
    alias: connector-moretonbay
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-moretonbay

  - name: magda-csw-connector
    version: 0.0.57-0
    alias: connector-neii
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-neii

  - name: magda-ckan-connector
    version: 0.0.57-0
    alias: connector-nsw
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-nsw

  - name: magda-csw-connector
    version: 0.0.57-0
    alias: connector-sdinsw
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-sdinsw

  - name: magda-ckan-connector
    version: 0.0.57-0
    alias: connector-qld
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-qld

  - name: magda-ckan-connector
    version: 0.0.57-0
    alias: connector-sa
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-sa

  - name: magda-project-open-data-connector
    version: 0.0.57-0
    alias: connector-southerngrampians
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-southerngrampians

  - name: magda-csw-connector
    version: 0.0.57-0
    alias: connector-listtas
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-listtas

  - name: magda-csw-connector
    version: 0.0.57-0
    alias: connector-tern
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-tern

  - name: magda-ckan-connector
    version: 0.0.57-0
    alias: connector-vic
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-vic

  - name: magda-ckan-connector
    version: 0.0.57-0
    alias: connector-wa
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-wa

  - name: magda-dap-connector
    version: 0.0.57-0
    alias: connector-dap
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-dap

  - name: magda-project-open-data-connector
    version: 0.0.57-0
    alias: connector-vic-cardinia
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-vic-cardinia

  - name: magda-project-open-data-connector
    version: 0.0.57-0
    alias: connector-nt-darwin
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-nt-darwin

  - name: magda-project-open-data-connector
    version: 0.0.57-0
    alias: connector-southern-grampians
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-southern-grampians

  - name: magda-esri-portal-connector
    version: 0.0.57-0
    alias: connector-esri-nsw
    repository: https://charts.magda.io
    tags:
      - connector-esri-nsw
