dependencies:
  - name: apidocs-server
    tags:
      - all
      - apidocs-server
  - name: authorization-api
    tags:
      - all
      - authorization-api
  - name: authorization-db
    tags:
      - all
      - authorization-db
  - name: combined-db
    tags:
      - all
      - combined-db
  - name: content-api
    tags:
      - all
      - content-api
  - name: content-db
    tags:
      - all
      - content-db
  - name: correspondence-api
    tags:
      - all
      - correspondence-api
  - name: elasticsearch
    tags:
      - all
      - elasticsearch
  - name: gateway
    tags:
      - all
      - gateway
  - name: indexer
    tags:
      - all
      - indexer
  - name: preview-map
    tags:
      - all
      - preview-map
  - name: registry-api
    tags:
      - all
      - registry-api
  - name: registry-db
    tags:
      - all
      - registry-db
  - name: search-api
    tags:
      - all
      - search-api
  - name: session-db
    tags:
      - all
      - session-db
  - name: web-server
    tags:
      - all
      - web-server
  - name: connectors
    tags:
      - all
      - connectors

# Deprecated or not currently used services
  - name: admin-api
    tags:
      - admin-api

# Minions
  - name: minion-broken-link
    tags:
      - minion-broken-link
  - name: minion-format
    tags:
      - minion-format
  - name: minion-linked-data-rating
    tags:
      - minion-linked-data-rating
  - name: minion-visualization
    tags:
      - minion-visualization

  - name: ingress
    tags:
      - ingress
