name: Build magda-web-server

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The branch or ref to deploy"
        required: true
        default: "next"

env:
  AWS_DEFAULT_REGION: ap-southeast-2

jobs:

  build-magda-web-server:
  
    runs-on: ubuntu-latest
  
    permissions:
      id-token: write
      contents: write
    
    steps:
      - name: Prepare Node 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Build magda-web-client
        run: yarn install && yarn run build
        working-directory: magda-web-client
      
      - name: Build magda-web-server
        run: yarn install && yarn run build
        working-directory: ./magda-web-server

      - name: Docker Build
        run: yarn run docker-build-prod
        working-directory: ./magda-web-server
        
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           role-to-assume: arn:aws:iam::940728446396:role/GitHubRole-Build-7QP2Q93CJ5GH
#           aws-region: ${{env.AWS_DEFAULT_REGION}}

#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Build, tag, and push docker image to Amazon ECR
#         env:
#           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           REPOSITORY: magda-web-service-test
#         run: |
#           docker build -t $REGISTRY/$REPOSITORY:${GITHUB_SHA::8} -f magda-web-server/Dockerfile magda-web-server
#           docker push $REGISTRY/$REPOSITORY:${GITHUB_SHA::8}
